// apps/vue-json-highlight/src/App.vue
<script setup lang="ts">
import { computed, reactive } from 'vue'
import ViewJson from './components/ViewJson.vue'
import HighlightAsJson from './components/HighlightAsJson.vue'

const state = reactive({ text: '', isLoading: false, error: null })
const json = computed(() => (state.text ? JSON.parse(state.text) : null))
async function loadData() {
  state.text = await (await fetch(`/data.json`)).text()
}

loadData()
</script>

<template>
  <div class="max-w-[960px] min-h-screen m-auto p-2">
    <h1 class="text-4xl font-bold leading-relaxed text-center">Vue JSON highlight 🍭</h1>
    <div class="flex gap-2 flex-col">
      <div id="json-text-placeholder" class="text-xs whitespace-pre-wrap bg-gray-100 p-4 rounded-md">
        <HighlightAsJson :text="state.text" />
      </div>
      <div id="json-placeholder" class="text-xs whitespace-pre-wrap bg-gray-100 p-4 rounded-md">
        <ViewJson :json="json" />
      </div>
      <div id="json-placeholder-ref" class="text-xs whitespace-pre-wrap bg-gray-100 p-4 rounded-md">
        {{ JSON.stringify(json, null, 2) }}
      </div>
    </div>
  </div>
</template>

// apps/react-json-highlight/src/components/App.tsx
import ViewJson from './ViewJson'
import { useEffect, useMemo, useState } from 'react'
import HighlightAsJson from './HighlightAsJson'

export default function App() {
  const [error, setError] = useState(null)
  const [isLoaded, setIsLoaded] = useState(false)
  const [text, setText] = useState<string>('null')
  const json = useMemo(() => JSON.parse(text), [text])

  useEffect(() => {
    fetch('/data.json')
      .then((res) => res.text())
      .then(
        (result) => {
          setIsLoaded(true)
          setText(result)
        },
        (error) => {
          setIsLoaded(true)
          setError(error)
        },
      )
  }, [])

  if (error) return <div>Error: {error.message}</div>
  if (!isLoaded) return <div>Loading...</div>

  return (
    <div className="max-w-[960px] min-h-screen m-auto p-2">
      <h1 className="text-4xl font-bold leading-relaxed text-center">React JSON highlight 🍭</h1>
      <div className="flex gap-2 flex-col">
        <pre id="json-text-placeholder" className="text-xs whitespace-pre-wrap bg-gray-100 p-4 rounded-md">
          <HighlightAsJson text={text} />
        </pre>
        <pre id="json-placeholder" className="text-xs whitespace-pre-wrap bg-gray-100 p-4 rounded-md">
          <ViewJson json={json} />
        </pre>
        <pre id="json-placeholder-ref" className="text-xs whitespace-pre-wrap bg-gray-100 p-4 rounded-md">
          {JSON.stringify(JSON.parse(text), null, 2)}
        </pre>
      </div>
    </div>
  )
}
