// apps/react-json-highlight/src/components/ViewJson.tsx
import { Fragment } from 'react'

type JSONValue = boolean | string | number | null | Array<JSONValue> | { [key in string]: JSONValue }

const Spaces = ({ n }: { n: number }) => <span className="text-gray-300">{'  '.repeat(n)}</span>
export default function ViewJson({ json, indent = 0 }: { json: JSONValue; indent?: number }) {
  if (json === null) return <span className="text-yellow-600">null</span>
  if (typeof json === 'boolean') return <span className="text-yellow-600">{json ? 'true' : 'false'}</span>
  if (typeof json === 'string') return <span className="text-green-700">"{json.replaceAll('"', '\\"')}"</span>
  if (typeof json === 'number') return <span className="text-yellow-600">{json}</span>

  if (Array.isArray(json))
    return (
      <>
        {'[\n'}
        {json.map((value, index, arr) => (
          <Fragment key={index}>
            <Spaces n={indent + 1} />
            <ViewJson json={value} indent={indent + 1} />
            {index !== arr.length - 1 ? ',\n' : ''}
          </Fragment>
        ))}
        {'\n'}
        <Spaces n={indent} />]
      </>
    )

  return (
    <>
      {'{\n'}
      {Object.entries(json).map(([key, value], index, arr) => (
        <Fragment key={index}>
          <Spaces n={indent + 1} />
          <span className="text-red-500">"{key}"</span>: <ViewJson json={value} indent={indent + 1} />
          {index !== arr.length - 1 ? ',\n' : ''}
        </Fragment>
      ))}
      {'\n'}
      <Spaces n={indent} /> {'}'}
    </>
  )
}

// apps/vue-json-highlight/src/components/ViewJson.vue
<script setup lang="ts">
import { defineProps } from 'vue'
import Spaces from './Spaces.vue'

type JSONValue = boolean | string | number | null | JSONValue | Record<string, JSONValue>

withDefaults(defineProps<{ json: JSONValue; indent?: number }>(), { indent: 0 })
</script>

<template>
  <span v-if="json === null" class="text-yellow-600">null</span>
  <span v-else-if="typeof json === 'boolean'" class="text-yellow-600">{{ json }}</span>
  <span v-else-if="typeof json === 'number'" class="text-yellow-600">{{ json }}</span>
  <span v-else-if="typeof json === 'string'" class="text-green-700">"{{ json.replaceAll('"', '\\"') }}"</span>

  <template v-else-if="Array.isArray(json)">
    <span>{{ '[\n' }}</span>
    <template v-for="(value, index) in json">
      <Spaces :n="indent + 1" />
      <ViewJson :json="value" :indent="indent + 1" />
      <template v-if="index !== json.length - 1">{{ ',\n' }}</template>
    </template>
    <span>{{ '\n' }}</span>
    <Spaces :n="indent" />
    <span>{{ ']' }}</span>
  </template>

  <template v-else>
    <span>{{ '{\n' }}</span>
    <template v-for="(value, key, index) in json">
      <Spaces :n="indent + 1" />
      <span class="text-red-500">"{{ key }}"</span>: <ViewJson :json="value" :indent="indent + 1" />
      <template v-if="index !== Object.keys(json).length - 1">{{ ',\n' }}</template>
    </template>
    <span>{{ '\n' }}</span>
    <Spaces :n="indent" />{{ '}' }}
  </template>
</template>
